-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2015.3
-- Copyright (C) 2015 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hlsExample_createReply is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    cr2checksum_V_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    cr2checksum_V_V_full_n : IN STD_LOGIC;
    cr2checksum_V_V_write : OUT STD_LOGIC;
    validBuffer_V_V_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    validBuffer_V_V_full_n : IN STD_LOGIC;
    validBuffer_V_V_write : OUT STD_LOGIC;
    parser2icmp_V_data_V_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    parser2icmp_V_data_V_empty_n : IN STD_LOGIC;
    parser2icmp_V_data_V_read : OUT STD_LOGIC;
    parser2icmp_V_strb_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    parser2icmp_V_strb_V_empty_n : IN STD_LOGIC;
    parser2icmp_V_strb_V_read : OUT STD_LOGIC;
    parser2icmp_V_user_V_dout : IN STD_LOGIC_VECTOR (127 downto 0);
    parser2icmp_V_user_V_empty_n : IN STD_LOGIC;
    parser2icmp_V_user_V_read : OUT STD_LOGIC;
    parser2icmp_V_last_V_dout : IN STD_LOGIC_VECTOR (0 downto 0);
    parser2icmp_V_last_V_empty_n : IN STD_LOGIC;
    parser2icmp_V_last_V_read : OUT STD_LOGIC;
    cr2dropper_V_data_V_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    cr2dropper_V_data_V_full_n : IN STD_LOGIC;
    cr2dropper_V_data_V_write : OUT STD_LOGIC;
    cr2dropper_V_strb_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    cr2dropper_V_strb_V_full_n : IN STD_LOGIC;
    cr2dropper_V_strb_V_write : OUT STD_LOGIC;
    cr2dropper_V_user_V_din : OUT STD_LOGIC_VECTOR (127 downto 0);
    cr2dropper_V_user_V_full_n : IN STD_LOGIC;
    cr2dropper_V_user_V_write : OUT STD_LOGIC;
    cr2dropper_V_last_V_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    cr2dropper_V_last_V_full_n : IN STD_LOGIC;
    cr2dropper_V_last_V_write : OUT STD_LOGIC );
end;


architecture behav of hlsExample_createReply is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm0_0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_st2_fsm1_1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_st0_fsm1_0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv18_3FFFF : STD_LOGIC_VECTOR (17 downto 0) := "111111111111111111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv18_40 : STD_LOGIC_VECTOR (17 downto 0) := "000000000001000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_8 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv18_3FFF8 : STD_LOGIC_VECTOR (17 downto 0) := "111111111111111000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm0 : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm0_0 : STD_LOGIC;
    signal ap_sig_bdd_23 : BOOLEAN;
    signal ap_CS_fsm1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding of ap_CS_fsm1 : signal is "none";
    signal ap_sig_cseq_ST_st0_fsm1_0 : STD_LOGIC;
    signal ap_sig_bdd_34 : BOOLEAN;
    signal parser2icmp_V_data_V0_status : STD_LOGIC;
    signal replyState_load_load_fu_276_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_nbreadreq_fu_154_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_78 : BOOLEAN;
    signal replyState_load_reg_753 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_reg_ppstg_replyState_load_reg_753_pp0_it0 : STD_LOGIC_VECTOR (3 downto 0);
    signal cr2dropper_V_data_V1_status : STD_LOGIC;
    signal tmp_8_reg_786 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_794 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_23_reg_798 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_reg_812 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_816 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_820 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_824 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_158 : BOOLEAN;
    signal ap_sig_cseq_ST_st2_fsm1_1 : STD_LOGIC;
    signal ap_sig_bdd_164 : BOOLEAN;
    signal replyState : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal crCurrWord_data_V : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal crCurrWord_strb_V : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal crCurrWord_user_V : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal crCurrWord_last_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal icmpChecksum_V : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal ipProto_V : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal ipChecksum_V : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal oldTTL : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_Val2_9_reg_757 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_strb_V_reg_766 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_user_V_reg_771 : STD_LOGIC_VECTOR (127 downto 0);
    signal tmp_last_V_reg_776 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_V_fu_308_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_V_reg_781 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_233_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_12_reg_802 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_28_fu_454_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_28_reg_807 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_cond1_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_598_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_reg_828 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_833 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_reg_833_pp0_it0 : STD_LOGIC_VECTOR (0 downto 0);
    signal parser2icmp_V_data_V0_update : STD_LOGIC;
    signal tmp_V_2_fu_636_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal cr2dropper_V_data_V1_update : STD_LOGIC;
    signal p_Result_16_fu_722_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_15_fu_737_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_14_fu_466_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_Result_7_fu_602_p5 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_1_fu_641_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_10_fu_667_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_3_fu_679_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_3_fu_710_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_s_fu_318_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_2_fu_350_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_1_fu_368_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_9_fu_390_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_2_fu_532_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_s_fu_336_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_3_fu_346_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_s_fu_386_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal buffer_V_1_fu_414_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_fu_458_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_Result_10_fu_424_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_11_fu_434_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_484_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_520_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_1_fu_524_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal buffer_V_fu_588_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Result_s_92_fu_653_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_4_fu_663_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_13_fu_703_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Result_8_fu_694_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_267_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_27_fu_691_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_24_fu_734_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_bdd_297 : BOOLEAN;
    signal ap_sig_bdd_110 : BOOLEAN;
    signal ap_sig_bdd_380 : BOOLEAN;
    signal ap_sig_bdd_56 : BOOLEAN;
    signal ap_sig_bdd_171 : BOOLEAN;
    signal ap_sig_bdd_633 : BOOLEAN;


begin




    -- the current state (ap_CS_fsm0) of the state machine. --
    ap_CS_fsm0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm0 <= ap_ST_st1_fsm0_0;
            else
                ap_CS_fsm0 <= ap_NS_fsm0;
            end if;
        end if;
    end process;


    -- the current state (ap_CS_fsm1) of the state machine. --
    ap_CS_fsm1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm1 <= ap_ST_st0_fsm1_0;
            else
                ap_CS_fsm1 <= ap_NS_fsm1;
            end if;
        end if;
    end process;


    -- ap_done_reg assign process. --
    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- crCurrWord_data_V assign process. --
    crCurrWord_data_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then 
                crCurrWord_data_V <= p_Result_7_fu_602_p5;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_4) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then 
                crCurrWord_data_V <= p_Result_14_fu_466_p5;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and (replyState = ap_const_lv4_5) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_3) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_2) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))))) then 
                crCurrWord_data_V <= parser2icmp_V_data_V_dout;
            end if; 
        end if;
    end process;

    -- icmpChecksum_V assign process. --
    icmpChecksum_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (ap_sig_bdd_297) then
                if (ap_sig_bdd_380) then 
                    icmpChecksum_V <= ap_const_lv18_3FFFF;
                elsif (ap_sig_bdd_110) then 
                    icmpChecksum_V <= p_3_fu_710_p2;
                elsif ((ap_reg_ppstg_replyState_load_reg_753_pp0_it0 = ap_const_lv4_9)) then 
                    icmpChecksum_V <= tmp_3_fu_679_p2;
                elsif ((ap_reg_ppstg_replyState_load_reg_753_pp0_it0 = ap_const_lv4_A)) then 
                    icmpChecksum_V <= tmp_10_fu_667_p2;
                elsif ((replyState_load_reg_753 = ap_const_lv4_B)) then 
                    icmpChecksum_V <= p_1_fu_641_p2;
                end if;
            end if; 
        end if;
    end process;

    -- ipChecksum_V assign process. --
    ipChecksum_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (ap_sig_bdd_171) then
                if (ap_sig_bdd_56) then 
                    ipChecksum_V <= p_2_fu_532_p2;
                elsif ((replyState_load_load_fu_276_p1 = ap_const_lv4_7)) then 
                    ipChecksum_V <= tmp_9_fu_390_p2;
                elsif ((replyState_load_load_fu_276_p1 = ap_const_lv4_8)) then 
                    ipChecksum_V <= tmp_1_fu_368_p2;
                elsif ((replyState_load_load_fu_276_p1 = ap_const_lv4_9)) then 
                    ipChecksum_V <= tmp_2_fu_350_p2;
                elsif ((replyState_load_load_fu_276_p1 = ap_const_lv4_A)) then 
                    ipChecksum_V <= p_s_fu_318_p2;
                end if;
            end if; 
        end if;
    end process;

    -- replyState assign process. --
    replyState_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then 
                replyState <= ap_const_lv4_1;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then 
                replyState <= ap_const_lv4_2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_2) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then 
                replyState <= ap_const_lv4_3;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_3) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then 
                replyState <= ap_const_lv4_4;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_4) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and (ap_const_lv1_0 = grp_fu_233_p1) and not((ap_const_lv1_0 = or_cond1_fu_508_p2)))) then 
                replyState <= ap_const_lv4_7;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and (replyState = ap_const_lv4_5) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and not((ap_const_lv1_0 = grp_fu_233_p1))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_4) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and not((ap_const_lv1_0 = grp_fu_233_p1))))) then 
                replyState <= ap_const_lv4_6;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and (replyState_load_load_fu_276_p1 = ap_const_lv4_6))) then 
                replyState <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and (replyState_load_load_fu_276_p1 = ap_const_lv4_7))) then 
                replyState <= ap_const_lv4_8;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and (replyState_load_load_fu_276_p1 = ap_const_lv4_8))) then 
                replyState <= ap_const_lv4_9;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and (replyState_load_load_fu_276_p1 = ap_const_lv4_9))) then 
                replyState <= ap_const_lv4_A;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and (replyState_load_load_fu_276_p1 = ap_const_lv4_A))) then 
                replyState <= ap_const_lv4_B;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and (replyState_load_load_fu_276_p1 = ap_const_lv4_B))) then 
                replyState <= ap_const_lv4_C;
            elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and (replyState_load_load_fu_276_p1 = ap_const_lv4_C)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_4) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and (ap_const_lv1_0 = grp_fu_233_p1) and (ap_const_lv1_0 = or_cond1_fu_508_p2)))) then 
                replyState <= ap_const_lv4_5;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and (replyState = ap_const_lv4_5) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_4) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_3) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_2) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))))) then
                crCurrWord_last_V <= parser2icmp_V_last_V_dout;
                crCurrWord_strb_V <= parser2icmp_V_strb_V_dout;
                crCurrWord_user_V <= parser2icmp_V_user_V_dout;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_2) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then
                ipProto_V <= parser2icmp_V_data_V_dout(63 downto 56);
                oldTTL <= parser2icmp_V_data_V_dout(55 downto 48);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_4) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and (ap_const_lv1_0 = grp_fu_233_p1))) then
                or_cond1_reg_812 <= or_cond1_fu_508_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_4) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then
                p_Result_12_reg_802 <= parser2icmp_V_data_V_dout(47 downto 32);
                tmp_28_reg_807 <= tmp_28_fu_454_p1;
                tmp_last_V_23_reg_798 <= parser2icmp_V_last_V_dout;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then
                p_Val2_9_reg_757 <= crCurrWord_data_V;
                replyState_load_reg_753 <= replyState;
                tmp_last_V_reg_776 <= crCurrWord_last_V;
                tmp_strb_V_reg_766 <= crCurrWord_strb_V;
                tmp_user_V_reg_771 <= crCurrWord_user_V;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then
                tmp_25_reg_828 <= tmp_25_fu_598_p1;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and (replyState = ap_const_lv4_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then
                tmp_4_reg_824 <= grp_nbreadreq_fu_154_p6;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and (replyState = ap_const_lv4_2) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then
                tmp_5_reg_820 <= grp_nbreadreq_fu_154_p6;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and (replyState = ap_const_lv4_3) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then
                tmp_6_reg_816 <= grp_nbreadreq_fu_154_p6;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and (replyState = ap_const_lv4_4) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then
                tmp_7_reg_794 <= grp_nbreadreq_fu_154_p6;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and (replyState = ap_const_lv4_5) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then
                tmp_8_reg_786 <= grp_nbreadreq_fu_154_p6;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))) and (replyState_load_load_fu_276_p1 = ap_const_lv4_B))) then
                tmp_V_reg_781 <= tmp_V_fu_308_p1;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and (replyState = ap_const_lv4_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then
                tmp_reg_833 <= grp_nbreadreq_fu_154_p6;
            end if;
        end if;
    end process;

    -- the next state (ap_NS_fsm1) of the state machine. --
    ap_NS_fsm1_assign_proc : process (ap_done_reg, ap_sig_cseq_ST_st1_fsm0_0, ap_CS_fsm1, ap_sig_bdd_78, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1)
    begin
        case ap_CS_fsm1 is
            when ap_ST_st2_fsm1_1 => 
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158)) and not(ap_sig_bdd_78))) then
                    ap_NS_fsm1 <= ap_ST_st2_fsm1_1;
                elsif ((not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158)) and (not((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and ap_sig_bdd_78)))) then
                    ap_NS_fsm1 <= ap_ST_st0_fsm1_0;
                else
                    ap_NS_fsm1 <= ap_ST_st2_fsm1_1;
                end if;
            when ap_ST_st0_fsm1_0 => 
                if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then
                    ap_NS_fsm1 <= ap_ST_st2_fsm1_1;
                else
                    ap_NS_fsm1 <= ap_ST_st0_fsm1_0;
                end if;
            when others =>  
                ap_NS_fsm1 <= "XX";
        end case;
    end process;

    -- the next state (ap_NS_fsm0) of the state machine. --
    ap_NS_fsm0_assign_proc : process (ap_done_reg, ap_CS_fsm0, ap_sig_bdd_78, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1)
    begin
        case ap_CS_fsm0 is
            when ap_ST_st1_fsm0_0 => 
                ap_NS_fsm0 <= ap_ST_st1_fsm0_0;
            when others =>  
                ap_NS_fsm0 <= "X";
        end case;
    end process;

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_done_reg, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm0_0, ap_sig_cseq_ST_st0_fsm1_0)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and (ap_const_logic_1 = ap_sig_cseq_ST_st0_fsm1_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_done_reg, ap_sig_cseq_ST_st1_fsm0_0, ap_sig_bdd_78, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_reg_ppstg_replyState_load_reg_753_pp0_it0 <= replyState_load_reg_753;
    ap_reg_ppstg_tmp_reg_833_pp0_it0 <= tmp_reg_833;

    -- ap_sig_bdd_110 assign process. --
    ap_sig_bdd_110_assign_proc : process(replyState_load_reg_753, tmp_7_reg_794)
    begin
                ap_sig_bdd_110 <= ((ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794)));
    end process;


    -- ap_sig_bdd_158 assign process. --
    ap_sig_bdd_158_assign_proc : process(cr2checksum_V_V_full_n, replyState_load_reg_753, cr2dropper_V_data_V1_status, tmp_8_reg_786, tmp_7_reg_794, validBuffer_V_V_full_n, tmp_last_V_23_reg_798, or_cond1_reg_812, tmp_6_reg_816, tmp_5_reg_820, tmp_4_reg_824)
    begin
                ap_sig_bdd_158 <= (((cr2checksum_V_V_full_n = ap_const_logic_0) and (replyState_load_reg_753 = ap_const_lv4_C)) or ((cr2checksum_V_V_full_n = ap_const_logic_0) and (replyState_load_reg_753 = ap_const_lv4_B)) or ((cr2dropper_V_data_V1_status = ap_const_logic_0) and (replyState_load_reg_753 = ap_const_lv4_6)) or ((cr2dropper_V_data_V1_status = ap_const_logic_0) and (ap_const_lv4_5 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_8_reg_786))) or ((cr2dropper_V_data_V1_status = ap_const_logic_0) and (ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794))) or ((ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794)) and (validBuffer_V_V_full_n = ap_const_logic_0) and (ap_const_lv1_0 = tmp_last_V_23_reg_798) and (ap_const_lv1_0 = or_cond1_reg_812)) or ((ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794)) and (validBuffer_V_V_full_n = ap_const_logic_0) and (ap_const_lv1_0 = tmp_last_V_23_reg_798) and not((ap_const_lv1_0 = or_cond1_reg_812))) or ((cr2dropper_V_data_V1_status = ap_const_logic_0) and (ap_const_lv4_3 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_6_reg_816))) or ((cr2dropper_V_data_V1_status = ap_const_logic_0) and (ap_const_lv4_2 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_5_reg_820))) or ((cr2dropper_V_data_V1_status = ap_const_logic_0) and (ap_const_lv4_1 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_4_reg_824))));
    end process;


    -- ap_sig_bdd_164 assign process. --
    ap_sig_bdd_164_assign_proc : process(ap_CS_fsm1)
    begin
                ap_sig_bdd_164 <= (ap_const_lv1_1 = ap_CS_fsm1(1 downto 1));
    end process;


    -- ap_sig_bdd_171 assign process. --
    ap_sig_bdd_171_assign_proc : process(ap_done_reg, ap_sig_cseq_ST_st1_fsm0_0, ap_sig_bdd_78, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1)
    begin
                ap_sig_bdd_171 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1)))));
    end process;


    -- ap_sig_bdd_23 assign process. --
    ap_sig_bdd_23_assign_proc : process(ap_CS_fsm0)
    begin
                ap_sig_bdd_23 <= (ap_CS_fsm0(0 downto 0) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_297 assign process. --
    ap_sig_bdd_297_assign_proc : process(ap_done_reg, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1)
    begin
                ap_sig_bdd_297 <= ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158)));
    end process;


    -- ap_sig_bdd_34 assign process. --
    ap_sig_bdd_34_assign_proc : process(ap_CS_fsm1)
    begin
                ap_sig_bdd_34 <= (ap_const_lv1_1 = ap_CS_fsm1(0 downto 0));
    end process;


    -- ap_sig_bdd_380 assign process. --
    ap_sig_bdd_380_assign_proc : process(ap_reg_ppstg_replyState_load_reg_753_pp0_it0, ap_reg_ppstg_tmp_reg_833_pp0_it0)
    begin
                ap_sig_bdd_380 <= ((ap_const_lv4_0 = ap_reg_ppstg_replyState_load_reg_753_pp0_it0) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_reg_833_pp0_it0)));
    end process;


    -- ap_sig_bdd_56 assign process. --
    ap_sig_bdd_56_assign_proc : process(grp_nbreadreq_fu_154_p6, replyState)
    begin
                ap_sig_bdd_56 <= (not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_3));
    end process;


    -- ap_sig_bdd_633 assign process. --
    ap_sig_bdd_633_assign_proc : process(ap_done_reg, replyState_load_reg_753, tmp_7_reg_794, tmp_last_V_23_reg_798, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1)
    begin
                ap_sig_bdd_633 <= ((ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794)) and (ap_const_lv1_0 = tmp_last_V_23_reg_798) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158)));
    end process;


    -- ap_sig_bdd_78 assign process. --
    ap_sig_bdd_78_assign_proc : process(ap_start, ap_done_reg, parser2icmp_V_data_V0_status, grp_nbreadreq_fu_154_p6, replyState)
    begin
                ap_sig_bdd_78 <= (((parser2icmp_V_data_V0_status = ap_const_logic_0) and (replyState = ap_const_lv4_5) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0))) or ((parser2icmp_V_data_V0_status = ap_const_logic_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_4)) or ((parser2icmp_V_data_V0_status = ap_const_logic_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_3)) or ((parser2icmp_V_data_V0_status = ap_const_logic_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_2)) or ((parser2icmp_V_data_V0_status = ap_const_logic_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_1)) or ((parser2icmp_V_data_V0_status = ap_const_logic_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_0)) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    -- ap_sig_cseq_ST_st0_fsm1_0 assign process. --
    ap_sig_cseq_ST_st0_fsm1_0_assign_proc : process(ap_sig_bdd_34)
    begin
        if (ap_sig_bdd_34) then 
            ap_sig_cseq_ST_st0_fsm1_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st0_fsm1_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st1_fsm0_0 assign process. --
    ap_sig_cseq_ST_st1_fsm0_0_assign_proc : process(ap_sig_bdd_23)
    begin
        if (ap_sig_bdd_23) then 
            ap_sig_cseq_ST_st1_fsm0_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm0_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st2_fsm1_1 assign process. --
    ap_sig_cseq_ST_st2_fsm1_1_assign_proc : process(ap_sig_bdd_164)
    begin
        if (ap_sig_bdd_164) then 
            ap_sig_cseq_ST_st2_fsm1_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm1_1 <= ap_const_logic_0;
        end if; 
    end process;

    buffer_V_1_fu_414_p4 <= crCurrWord_data_V(47 downto 32);
    buffer_V_fu_588_p4 <= crCurrWord_data_V(47 downto 16);

    -- cr2checksum_V_V_din assign process. --
    cr2checksum_V_V_din_assign_proc : process(replyState_load_reg_753, tmp_V_reg_781, tmp_V_2_fu_636_p1, ap_sig_bdd_297)
    begin
        if (ap_sig_bdd_297) then
            if ((replyState_load_reg_753 = ap_const_lv4_B)) then 
                cr2checksum_V_V_din <= tmp_V_reg_781;
            elsif ((replyState_load_reg_753 = ap_const_lv4_C)) then 
                cr2checksum_V_V_din <= tmp_V_2_fu_636_p1;
            else 
                cr2checksum_V_V_din <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            cr2checksum_V_V_din <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    -- cr2checksum_V_V_write assign process. --
    cr2checksum_V_V_write_assign_proc : process(ap_done_reg, replyState_load_reg_753, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1)
    begin
        if ((((replyState_load_reg_753 = ap_const_lv4_C) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((replyState_load_reg_753 = ap_const_lv4_B) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))))) then 
            cr2checksum_V_V_write <= ap_const_logic_1;
        else 
            cr2checksum_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    cr2dropper_V_data_V1_status <= (cr2dropper_V_data_V_full_n and cr2dropper_V_strb_V_full_n and cr2dropper_V_user_V_full_n and cr2dropper_V_last_V_full_n);

    -- cr2dropper_V_data_V1_update assign process. --
    cr2dropper_V_data_V1_update_assign_proc : process(ap_done_reg, replyState_load_reg_753, tmp_8_reg_786, tmp_7_reg_794, tmp_6_reg_816, tmp_5_reg_820, tmp_4_reg_824, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1)
    begin
        if ((((replyState_load_reg_753 = ap_const_lv4_6) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_5 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_8_reg_786)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_3 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_6_reg_816)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_2 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_5_reg_820)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_1 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_4_reg_824)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))))) then 
            cr2dropper_V_data_V1_update <= ap_const_logic_1;
        else 
            cr2dropper_V_data_V1_update <= ap_const_logic_0;
        end if; 
    end process;


    -- cr2dropper_V_data_V_din assign process. --
    cr2dropper_V_data_V_din_assign_proc : process(ap_done_reg, replyState_load_reg_753, tmp_8_reg_786, tmp_7_reg_794, tmp_6_reg_816, tmp_5_reg_820, tmp_4_reg_824, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1, p_Val2_9_reg_757, p_Result_16_fu_722_p5, p_Result_15_fu_737_p4)
    begin
        if (((ap_const_lv4_1 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_4_reg_824)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158)))) then 
            cr2dropper_V_data_V_din <= p_Result_15_fu_737_p4;
        elsif (((ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158)))) then 
            cr2dropper_V_data_V_din <= p_Result_16_fu_722_p5;
        elsif ((((replyState_load_reg_753 = ap_const_lv4_6) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_5 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_8_reg_786)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_3 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_6_reg_816)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_2 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_5_reg_820)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))))) then 
            cr2dropper_V_data_V_din <= p_Val2_9_reg_757;
        else 
            cr2dropper_V_data_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    cr2dropper_V_data_V_write <= cr2dropper_V_data_V1_update;

    -- cr2dropper_V_last_V_din assign process. --
    cr2dropper_V_last_V_din_assign_proc : process(ap_done_reg, replyState_load_reg_753, tmp_8_reg_786, tmp_7_reg_794, tmp_6_reg_816, tmp_5_reg_820, tmp_4_reg_824, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1, tmp_last_V_reg_776)
    begin
        if ((((ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_1 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_4_reg_824)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))))) then 
            cr2dropper_V_last_V_din <= ap_const_lv1_0;
        elsif ((((replyState_load_reg_753 = ap_const_lv4_6) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_5 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_8_reg_786)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_3 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_6_reg_816)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_2 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_5_reg_820)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))))) then 
            cr2dropper_V_last_V_din <= tmp_last_V_reg_776;
        else 
            cr2dropper_V_last_V_din <= "X";
        end if; 
    end process;

    cr2dropper_V_last_V_write <= cr2dropper_V_data_V1_update;

    -- cr2dropper_V_strb_V_din assign process. --
    cr2dropper_V_strb_V_din_assign_proc : process(ap_done_reg, replyState_load_reg_753, tmp_8_reg_786, tmp_7_reg_794, tmp_6_reg_816, tmp_5_reg_820, tmp_4_reg_824, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1, tmp_strb_V_reg_766)
    begin
        if ((((ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_1 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_4_reg_824)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))))) then 
            cr2dropper_V_strb_V_din <= ap_const_lv8_FF;
        elsif ((((replyState_load_reg_753 = ap_const_lv4_6) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_5 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_8_reg_786)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_3 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_6_reg_816)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_2 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_5_reg_820)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))))) then 
            cr2dropper_V_strb_V_din <= tmp_strb_V_reg_766;
        else 
            cr2dropper_V_strb_V_din <= "XXXXXXXX";
        end if; 
    end process;

    cr2dropper_V_strb_V_write <= cr2dropper_V_data_V1_update;

    -- cr2dropper_V_user_V_din assign process. --
    cr2dropper_V_user_V_din_assign_proc : process(ap_done_reg, replyState_load_reg_753, tmp_8_reg_786, tmp_7_reg_794, tmp_6_reg_816, tmp_5_reg_820, tmp_4_reg_824, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1, tmp_user_V_reg_771)
    begin
        if ((((ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_1 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_4_reg_824)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))))) then 
            cr2dropper_V_user_V_din <= ap_const_lv128_lc_1;
        elsif ((((replyState_load_reg_753 = ap_const_lv4_6) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_5 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_8_reg_786)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_3 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_6_reg_816)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_2 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_5_reg_820)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))))) then 
            cr2dropper_V_user_V_din <= tmp_user_V_reg_771;
        else 
            cr2dropper_V_user_V_din <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    cr2dropper_V_user_V_write <= cr2dropper_V_data_V1_update;
    grp_fu_233_p1 <= parser2icmp_V_last_V_dout;
    grp_fu_267_p4 <= p_Val2_9_reg_757(63 downto 48);
    grp_nbreadreq_fu_154_p6 <= (0=>(parser2icmp_V_data_V_empty_n and parser2icmp_V_strb_V_empty_n and parser2icmp_V_user_V_empty_n and parser2icmp_V_last_V_empty_n), others=>'-');
    or_cond1_fu_508_p2 <= (tmp1_fu_502_p2 and tmp_12_fu_484_p2);
    p_1_fu_641_p2 <= (icmpChecksum_V xor ap_const_lv18_3FFFF);
    p_2_fu_532_p2 <= (p_Result_1_fu_524_p3 xor ap_const_lv18_3FFFF);
    p_3_fu_710_p2 <= (p_Result_13_fu_703_p3 xor ap_const_lv18_3FFFF);
    p_Result_10_fu_424_p4 <= parser2icmp_V_data_V_dout(23 downto 16);
    p_Result_11_fu_434_p4 <= parser2icmp_V_data_V_dout(31 downto 24);
    p_Result_13_fu_703_p3 <= (ap_const_lv2_3 & p_Result_12_reg_802);
    p_Result_14_fu_466_p5 <= (parser2icmp_V_data_V_dout(63 downto 24) & tmp_11_fu_458_p3);
    p_Result_15_fu_737_p4 <= ((tmp_24_fu_734_p1 & tmp_25_reg_828) & grp_fu_267_p4);
    p_Result_16_fu_722_p5 <= (((p_Result_8_fu_694_p4 & tmp_28_reg_807) & grp_fu_267_p4) & tmp_27_fu_691_p1);
    p_Result_1_fu_524_p3 <= (ap_const_lv2_3 & tmp_26_fu_520_p1);
    p_Result_3_fu_346_p1 <= std_logic_vector(resize(unsigned(p_Result_s_fu_336_p4),18));
    p_Result_4_fu_663_p1 <= std_logic_vector(resize(unsigned(p_Result_s_92_fu_653_p4),18));
    p_Result_7_fu_602_p5 <= (parser2icmp_V_data_V_dout(63 downto 32) & buffer_V_fu_588_p4);
    p_Result_8_fu_694_p4 <= p_Val2_9_reg_757(31 downto 16);
    p_Result_s_92_fu_653_p4 <= icmpChecksum_V(17 downto 16);
    p_Result_s_fu_336_p4 <= ipChecksum_V(17 downto 16);
    p_s_fu_318_p2 <= (ipChecksum_V xor ap_const_lv18_3FFFF);
    parser2icmp_V_data_V0_status <= (parser2icmp_V_data_V_empty_n and parser2icmp_V_strb_V_empty_n and parser2icmp_V_user_V_empty_n and parser2icmp_V_last_V_empty_n);

    -- parser2icmp_V_data_V0_update assign process. --
    parser2icmp_V_data_V0_update_assign_proc : process(ap_done_reg, ap_sig_cseq_ST_st1_fsm0_0, grp_nbreadreq_fu_154_p6, ap_sig_bdd_78, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1, replyState)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and (replyState = ap_const_lv4_5) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_4) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_3) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_2) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm0_0) and not((grp_nbreadreq_fu_154_p6 = ap_const_lv1_0)) and (replyState = ap_const_lv4_0) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_78 or (ap_sig_bdd_158 and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1))))))) then 
            parser2icmp_V_data_V0_update <= ap_const_logic_1;
        else 
            parser2icmp_V_data_V0_update <= ap_const_logic_0;
        end if; 
    end process;

    parser2icmp_V_data_V_read <= parser2icmp_V_data_V0_update;
    parser2icmp_V_last_V_read <= parser2icmp_V_data_V0_update;
    parser2icmp_V_strb_V_read <= parser2icmp_V_data_V0_update;
    parser2icmp_V_user_V_read <= parser2icmp_V_data_V0_update;
    replyState_load_load_fu_276_p1 <= replyState;
    tmp1_fu_502_p2 <= (tmp_13_fu_490_p2 and tmp_14_fu_496_p2);
    tmp_10_fu_667_p2 <= std_logic_vector(unsigned(icmpChecksum_V) + unsigned(p_Result_4_fu_663_p1));
    tmp_11_fu_458_p3 <= (ap_const_lv8_0 & buffer_V_1_fu_414_p4);
    tmp_12_fu_484_p2 <= "1" when (ipProto_V = ap_const_lv8_1) else "0";
    tmp_13_fu_490_p2 <= "1" when (p_Result_10_fu_424_p4 = ap_const_lv8_8) else "0";
    tmp_14_fu_496_p2 <= "1" when (p_Result_11_fu_434_p4 = ap_const_lv8_0) else "0";
    tmp_1_fu_368_p2 <= std_logic_vector(unsigned(ipChecksum_V) + unsigned(ap_const_lv18_40));
    tmp_24_fu_734_p1 <= p_Val2_9_reg_757(16 - 1 downto 0);
    tmp_25_fu_598_p1 <= parser2icmp_V_data_V_dout(32 - 1 downto 0);
    tmp_26_fu_520_p1 <= parser2icmp_V_data_V_dout(16 - 1 downto 0);
    tmp_27_fu_691_p1 <= p_Val2_9_reg_757(16 - 1 downto 0);
    tmp_28_fu_454_p1 <= parser2icmp_V_data_V_dout(16 - 1 downto 0);
    tmp_2_fu_350_p2 <= std_logic_vector(unsigned(ipChecksum_V) + unsigned(p_Result_3_fu_346_p1));
    tmp_3_fu_679_p2 <= std_logic_vector(unsigned(icmpChecksum_V) + unsigned(ap_const_lv18_3FFF8));
    tmp_9_fu_390_p2 <= std_logic_vector(unsigned(ipChecksum_V) - unsigned(tmp_s_fu_386_p1));
    tmp_V_2_fu_636_p1 <= icmpChecksum_V(16 - 1 downto 0);
    tmp_V_fu_308_p1 <= ipChecksum_V(16 - 1 downto 0);
    tmp_s_fu_386_p1 <= std_logic_vector(resize(unsigned(oldTTL),18));

    -- validBuffer_V_V_din assign process. --
    validBuffer_V_V_din_assign_proc : process(or_cond1_reg_812, ap_sig_bdd_633)
    begin
        if (ap_sig_bdd_633) then
            if (not((ap_const_lv1_0 = or_cond1_reg_812))) then 
                validBuffer_V_V_din <= ap_const_lv1_1;
            elsif ((ap_const_lv1_0 = or_cond1_reg_812)) then 
                validBuffer_V_V_din <= ap_const_lv1_0;
            else 
                validBuffer_V_V_din <= "X";
            end if;
        else 
            validBuffer_V_V_din <= "X";
        end if; 
    end process;


    -- validBuffer_V_V_write assign process. --
    validBuffer_V_V_write_assign_proc : process(ap_done_reg, replyState_load_reg_753, tmp_7_reg_794, tmp_last_V_23_reg_798, or_cond1_reg_812, ap_sig_bdd_158, ap_sig_cseq_ST_st2_fsm1_1)
    begin
        if ((((ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794)) and (ap_const_lv1_0 = tmp_last_V_23_reg_798) and (ap_const_lv1_0 = or_cond1_reg_812) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))) or ((ap_const_lv4_4 = replyState_load_reg_753) and not((ap_const_lv1_0 = tmp_7_reg_794)) and (ap_const_lv1_0 = tmp_last_V_23_reg_798) and not((ap_const_lv1_0 = or_cond1_reg_812)) and (ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm1_1) and not(((ap_done_reg = ap_const_logic_1) or ap_sig_bdd_158))))) then 
            validBuffer_V_V_write <= ap_const_logic_1;
        else 
            validBuffer_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
