// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hlsExample_createReply (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        cr2checksum_V_V_din,
        cr2checksum_V_V_full_n,
        cr2checksum_V_V_write,
        validBuffer_V_V_din,
        validBuffer_V_V_full_n,
        validBuffer_V_V_write,
        parser2icmp_V_data_V_dout,
        parser2icmp_V_data_V_empty_n,
        parser2icmp_V_data_V_read,
        parser2icmp_V_strb_V_dout,
        parser2icmp_V_strb_V_empty_n,
        parser2icmp_V_strb_V_read,
        parser2icmp_V_user_V_dout,
        parser2icmp_V_user_V_empty_n,
        parser2icmp_V_user_V_read,
        parser2icmp_V_last_V_dout,
        parser2icmp_V_last_V_empty_n,
        parser2icmp_V_last_V_read,
        cr2dropper_V_data_V_din,
        cr2dropper_V_data_V_full_n,
        cr2dropper_V_data_V_write,
        cr2dropper_V_strb_V_din,
        cr2dropper_V_strb_V_full_n,
        cr2dropper_V_strb_V_write,
        cr2dropper_V_user_V_din,
        cr2dropper_V_user_V_full_n,
        cr2dropper_V_user_V_write,
        cr2dropper_V_last_V_din,
        cr2dropper_V_last_V_full_n,
        cr2dropper_V_last_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm0_0 = 1'b1;
parameter    ap_ST_st2_fsm1_1 = 2'b10;
parameter    ap_ST_st0_fsm1_0 = 2'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv4_5 = 4'b101;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv4_4 = 4'b100;
parameter    ap_const_lv4_3 = 4'b11;
parameter    ap_const_lv4_2 = 4'b10;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv4_C = 4'b1100;
parameter    ap_const_lv4_B = 4'b1011;
parameter    ap_const_lv4_6 = 4'b110;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv128_lc_1 = 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv4_A = 4'b1010;
parameter    ap_const_lv4_9 = 4'b1001;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_7 = 4'b111;
parameter    ap_const_lv18_3FFFF = 18'b111111111111111111;
parameter    ap_const_lv32_30 = 32'b110000;
parameter    ap_const_lv32_3F = 32'b111111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv18_40 = 18'b1000000;
parameter    ap_const_lv32_20 = 32'b100000;
parameter    ap_const_lv32_2F = 32'b101111;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_18 = 32'b11000;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv8_1 = 8'b1;
parameter    ap_const_lv8_8 = 8'b1000;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv32_37 = 32'b110111;
parameter    ap_const_lv32_38 = 32'b111000;
parameter    ap_const_lv18_3FFF8 = 18'b111111111111111000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [15:0] cr2checksum_V_V_din;
input   cr2checksum_V_V_full_n;
output   cr2checksum_V_V_write;
output  [0:0] validBuffer_V_V_din;
input   validBuffer_V_V_full_n;
output   validBuffer_V_V_write;
input  [63:0] parser2icmp_V_data_V_dout;
input   parser2icmp_V_data_V_empty_n;
output   parser2icmp_V_data_V_read;
input  [7:0] parser2icmp_V_strb_V_dout;
input   parser2icmp_V_strb_V_empty_n;
output   parser2icmp_V_strb_V_read;
input  [127:0] parser2icmp_V_user_V_dout;
input   parser2icmp_V_user_V_empty_n;
output   parser2icmp_V_user_V_read;
input  [0:0] parser2icmp_V_last_V_dout;
input   parser2icmp_V_last_V_empty_n;
output   parser2icmp_V_last_V_read;
output  [63:0] cr2dropper_V_data_V_din;
input   cr2dropper_V_data_V_full_n;
output   cr2dropper_V_data_V_write;
output  [7:0] cr2dropper_V_strb_V_din;
input   cr2dropper_V_strb_V_full_n;
output   cr2dropper_V_strb_V_write;
output  [127:0] cr2dropper_V_user_V_din;
input   cr2dropper_V_user_V_full_n;
output   cr2dropper_V_user_V_write;
output  [0:0] cr2dropper_V_last_V_din;
input   cr2dropper_V_last_V_full_n;
output   cr2dropper_V_last_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] cr2checksum_V_V_din;
reg cr2checksum_V_V_write;
reg[0:0] validBuffer_V_V_din;
reg validBuffer_V_V_write;
reg[63:0] cr2dropper_V_data_V_din;
reg[7:0] cr2dropper_V_strb_V_din;
reg[127:0] cr2dropper_V_user_V_din;
reg[0:0] cr2dropper_V_last_V_din;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm0 = 1'b1;
reg    ap_sig_cseq_ST_st1_fsm0_0;
reg    ap_sig_bdd_23;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm1 = 2'b1;
reg    ap_sig_cseq_ST_st0_fsm1_0;
reg    ap_sig_bdd_34;
wire    parser2icmp_V_data_V0_status;
wire   [3:0] replyState_load_load_fu_276_p1;
wire   [0:0] grp_nbreadreq_fu_154_p6;
reg    ap_sig_bdd_78;
reg   [3:0] replyState_load_reg_753;
wire   [3:0] ap_reg_ppstg_replyState_load_reg_753_pp0_it0;
wire    cr2dropper_V_data_V1_status;
reg   [0:0] tmp_8_reg_786;
reg   [0:0] tmp_7_reg_794;
reg   [0:0] tmp_last_V_23_reg_798;
reg   [0:0] or_cond1_reg_812;
reg   [0:0] tmp_6_reg_816;
reg   [0:0] tmp_5_reg_820;
reg   [0:0] tmp_4_reg_824;
reg    ap_sig_bdd_158;
reg    ap_sig_cseq_ST_st2_fsm1_1;
reg    ap_sig_bdd_164;
reg   [3:0] replyState = 4'b0000;
reg   [63:0] crCurrWord_data_V = 64'b0000000000000000000000000000000000000000000000000000000000000000;
reg   [7:0] crCurrWord_strb_V = 8'b00000000;
reg   [127:0] crCurrWord_user_V = 128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
reg   [0:0] crCurrWord_last_V = 1'b0;
reg   [17:0] icmpChecksum_V = 18'b000000000000000000;
reg   [7:0] ipProto_V = 8'b00000000;
reg   [17:0] ipChecksum_V = 18'b000000000000000000;
reg   [7:0] oldTTL = 8'b00000000;
reg   [63:0] p_Val2_9_reg_757;
reg   [7:0] tmp_strb_V_reg_766;
reg   [127:0] tmp_user_V_reg_771;
reg   [0:0] tmp_last_V_reg_776;
wire   [15:0] tmp_V_fu_308_p1;
reg   [15:0] tmp_V_reg_781;
wire   [0:0] grp_fu_233_p1;
reg   [15:0] p_Result_12_reg_802;
wire   [15:0] tmp_28_fu_454_p1;
reg   [15:0] tmp_28_reg_807;
wire   [0:0] or_cond1_fu_508_p2;
wire   [31:0] tmp_25_fu_598_p1;
reg   [31:0] tmp_25_reg_828;
reg   [0:0] tmp_reg_833;
wire   [0:0] ap_reg_ppstg_tmp_reg_833_pp0_it0;
reg    parser2icmp_V_data_V0_update;
wire   [15:0] tmp_V_2_fu_636_p1;
reg    cr2dropper_V_data_V1_update;
wire   [63:0] p_Result_16_fu_722_p5;
wire   [63:0] p_Result_15_fu_737_p4;
wire   [63:0] p_Result_14_fu_466_p5;
wire   [63:0] p_Result_7_fu_602_p5;
wire   [17:0] p_1_fu_641_p2;
wire   [17:0] tmp_10_fu_667_p2;
wire   [17:0] tmp_3_fu_679_p2;
wire   [17:0] p_3_fu_710_p2;
wire   [17:0] p_s_fu_318_p2;
wire   [17:0] tmp_2_fu_350_p2;
wire   [17:0] tmp_1_fu_368_p2;
wire   [17:0] tmp_9_fu_390_p2;
wire   [17:0] p_2_fu_532_p2;
wire   [1:0] p_Result_s_fu_336_p4;
wire   [17:0] p_Result_3_fu_346_p1;
wire   [17:0] tmp_s_fu_386_p1;
wire   [15:0] buffer_V_1_fu_414_p4;
wire   [23:0] tmp_11_fu_458_p3;
wire   [7:0] p_Result_10_fu_424_p4;
wire   [7:0] p_Result_11_fu_434_p4;
wire   [0:0] tmp_13_fu_490_p2;
wire   [0:0] tmp_14_fu_496_p2;
wire   [0:0] tmp1_fu_502_p2;
wire   [0:0] tmp_12_fu_484_p2;
wire   [15:0] tmp_26_fu_520_p1;
wire   [17:0] p_Result_1_fu_524_p3;
wire   [31:0] buffer_V_fu_588_p4;
wire   [1:0] p_Result_s_92_fu_653_p4;
wire   [17:0] p_Result_4_fu_663_p1;
wire   [17:0] p_Result_13_fu_703_p3;
wire   [15:0] p_Result_8_fu_694_p4;
wire   [15:0] grp_fu_267_p4;
wire   [15:0] tmp_27_fu_691_p1;
wire   [15:0] tmp_24_fu_734_p1;
reg   [0:0] ap_NS_fsm0;
reg   [1:0] ap_NS_fsm1;
reg    ap_sig_bdd_297;
reg    ap_sig_bdd_110;
reg    ap_sig_bdd_380;
reg    ap_sig_bdd_56;
reg    ap_sig_bdd_171;
reg    ap_sig_bdd_633;




/// the current state (ap_CS_fsm0) of the state machine. ///
always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm0
    if (ap_rst == 1'b1) begin
        ap_CS_fsm0 <= ap_ST_st1_fsm0_0;
    end else begin
        ap_CS_fsm0 <= ap_NS_fsm0;
    end
end

/// the current state (ap_CS_fsm1) of the state machine. ///
always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm1
    if (ap_rst == 1'b1) begin
        ap_CS_fsm1 <= ap_ST_st0_fsm1_0;
    end else begin
        ap_CS_fsm1 <= ap_NS_fsm1;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        crCurrWord_data_V <= p_Result_7_fu_602_p5;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_4) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        crCurrWord_data_V <= p_Result_14_fu_466_p5;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (replyState == ap_const_lv4_5) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_3) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_2) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))))) begin
        crCurrWord_data_V <= parser2icmp_V_data_V_dout;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (ap_sig_bdd_297) begin
        if (ap_sig_bdd_380) begin
            icmpChecksum_V <= ap_const_lv18_3FFFF;
        end else if (ap_sig_bdd_110) begin
            icmpChecksum_V <= p_3_fu_710_p2;
        end else if ((ap_reg_ppstg_replyState_load_reg_753_pp0_it0 == ap_const_lv4_9)) begin
            icmpChecksum_V <= tmp_3_fu_679_p2;
        end else if ((ap_reg_ppstg_replyState_load_reg_753_pp0_it0 == ap_const_lv4_A)) begin
            icmpChecksum_V <= tmp_10_fu_667_p2;
        end else if ((replyState_load_reg_753 == ap_const_lv4_B)) begin
            icmpChecksum_V <= p_1_fu_641_p2;
        end
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (ap_sig_bdd_171) begin
        if (ap_sig_bdd_56) begin
            ipChecksum_V <= p_2_fu_532_p2;
        end else if ((replyState_load_load_fu_276_p1 == ap_const_lv4_7)) begin
            ipChecksum_V <= tmp_9_fu_390_p2;
        end else if ((replyState_load_load_fu_276_p1 == ap_const_lv4_8)) begin
            ipChecksum_V <= tmp_1_fu_368_p2;
        end else if ((replyState_load_load_fu_276_p1 == ap_const_lv4_9)) begin
            ipChecksum_V <= tmp_2_fu_350_p2;
        end else if ((replyState_load_load_fu_276_p1 == ap_const_lv4_A)) begin
            ipChecksum_V <= p_s_fu_318_p2;
        end
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        replyState <= ap_const_lv4_1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        replyState <= ap_const_lv4_2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_2) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        replyState <= ap_const_lv4_3;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_3) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        replyState <= ap_const_lv4_4;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_4) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & (ap_const_lv1_0 == grp_fu_233_p1) & ~(ap_const_lv1_0 == or_cond1_fu_508_p2))) begin
        replyState <= ap_const_lv4_7;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (replyState == ap_const_lv4_5) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & ~(ap_const_lv1_0 == grp_fu_233_p1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_4) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & ~(ap_const_lv1_0 == grp_fu_233_p1)))) begin
        replyState <= ap_const_lv4_6;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & (replyState_load_load_fu_276_p1 == ap_const_lv4_6))) begin
        replyState <= ap_const_lv4_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & (replyState_load_load_fu_276_p1 == ap_const_lv4_7))) begin
        replyState <= ap_const_lv4_8;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & (replyState_load_load_fu_276_p1 == ap_const_lv4_8))) begin
        replyState <= ap_const_lv4_9;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & (replyState_load_load_fu_276_p1 == ap_const_lv4_9))) begin
        replyState <= ap_const_lv4_A;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & (replyState_load_load_fu_276_p1 == ap_const_lv4_A))) begin
        replyState <= ap_const_lv4_B;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & (replyState_load_load_fu_276_p1 == ap_const_lv4_B))) begin
        replyState <= ap_const_lv4_C;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & (replyState_load_load_fu_276_p1 == ap_const_lv4_C)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_4) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & (ap_const_lv1_0 == grp_fu_233_p1) & (ap_const_lv1_0 == or_cond1_fu_508_p2)))) begin
        replyState <= ap_const_lv4_5;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (replyState == ap_const_lv4_5) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_4) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_3) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_2) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))))) begin
        crCurrWord_last_V <= parser2icmp_V_last_V_dout;
        crCurrWord_strb_V <= parser2icmp_V_strb_V_dout;
        crCurrWord_user_V <= parser2icmp_V_user_V_dout;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_2) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        ipProto_V <= {{parser2icmp_V_data_V_dout[ap_const_lv32_3F : ap_const_lv32_38]}};
        oldTTL <= {{parser2icmp_V_data_V_dout[ap_const_lv32_37 : ap_const_lv32_30]}};
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_4) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & (ap_const_lv1_0 == grp_fu_233_p1))) begin
        or_cond1_reg_812 <= or_cond1_fu_508_p2;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_4) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        p_Result_12_reg_802 <= {{parser2icmp_V_data_V_dout[ap_const_lv32_2F : ap_const_lv32_20]}};
        tmp_28_reg_807 <= tmp_28_fu_454_p1;
        tmp_last_V_23_reg_798 <= parser2icmp_V_last_V_dout;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        p_Val2_9_reg_757 <= crCurrWord_data_V;
        replyState_load_reg_753 <= replyState;
        tmp_last_V_reg_776 <= crCurrWord_last_V;
        tmp_strb_V_reg_766 <= crCurrWord_strb_V;
        tmp_user_V_reg_771 <= crCurrWord_user_V;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_25_reg_828 <= tmp_25_fu_598_p1;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (replyState == ap_const_lv4_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_4_reg_824 <= grp_nbreadreq_fu_154_p6;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (replyState == ap_const_lv4_2) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_5_reg_820 <= grp_nbreadreq_fu_154_p6;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (replyState == ap_const_lv4_3) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_6_reg_816 <= grp_nbreadreq_fu_154_p6;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (replyState == ap_const_lv4_4) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_7_reg_794 <= grp_nbreadreq_fu_154_p6;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (replyState == ap_const_lv4_5) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_8_reg_786 <= grp_nbreadreq_fu_154_p6;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & (replyState_load_load_fu_276_p1 == ap_const_lv4_B))) begin
        tmp_V_reg_781 <= tmp_V_fu_308_p1;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (replyState == ap_const_lv4_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_reg_833 <= grp_nbreadreq_fu_154_p6;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm0_0 or ap_sig_cseq_ST_st0_fsm1_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st0_fsm1_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st1_fsm0_0 or ap_sig_bdd_78 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st0_fsm1_0 assign process. ///
always @ (ap_sig_bdd_34) begin
    if (ap_sig_bdd_34) begin
        ap_sig_cseq_ST_st0_fsm1_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st0_fsm1_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm0_0 assign process. ///
always @ (ap_sig_bdd_23) begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_st1_fsm0_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm0_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm1_1 assign process. ///
always @ (ap_sig_bdd_164) begin
    if (ap_sig_bdd_164) begin
        ap_sig_cseq_ST_st2_fsm1_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm1_1 = ap_const_logic_0;
    end
end

/// cr2checksum_V_V_din assign process. ///
always @ (replyState_load_reg_753 or tmp_V_reg_781 or tmp_V_2_fu_636_p1 or ap_sig_bdd_297) begin
    if (ap_sig_bdd_297) begin
        if ((replyState_load_reg_753 == ap_const_lv4_B)) begin
            cr2checksum_V_V_din = tmp_V_reg_781;
        end else if ((replyState_load_reg_753 == ap_const_lv4_C)) begin
            cr2checksum_V_V_din = tmp_V_2_fu_636_p1;
        end else begin
            cr2checksum_V_V_din = 'bx;
        end
    end else begin
        cr2checksum_V_V_din = 'bx;
    end
end

/// cr2checksum_V_V_write assign process. ///
always @ (ap_done_reg or replyState_load_reg_753 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1) begin
    if ((((replyState_load_reg_753 == ap_const_lv4_C) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((replyState_load_reg_753 == ap_const_lv4_B) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)))) begin
        cr2checksum_V_V_write = ap_const_logic_1;
    end else begin
        cr2checksum_V_V_write = ap_const_logic_0;
    end
end

/// cr2dropper_V_data_V1_update assign process. ///
always @ (ap_done_reg or replyState_load_reg_753 or tmp_8_reg_786 or tmp_7_reg_794 or tmp_6_reg_816 or tmp_5_reg_820 or tmp_4_reg_824 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1) begin
    if ((((replyState_load_reg_753 == ap_const_lv4_6) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_5 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_8_reg_786) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_3 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_6_reg_816) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_2 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_5_reg_820) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_1 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_4_reg_824) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)))) begin
        cr2dropper_V_data_V1_update = ap_const_logic_1;
    end else begin
        cr2dropper_V_data_V1_update = ap_const_logic_0;
    end
end

/// cr2dropper_V_data_V_din assign process. ///
always @ (ap_done_reg or replyState_load_reg_753 or tmp_8_reg_786 or tmp_7_reg_794 or tmp_6_reg_816 or tmp_5_reg_820 or tmp_4_reg_824 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1 or p_Val2_9_reg_757 or p_Result_16_fu_722_p5 or p_Result_15_fu_737_p4) begin
    if (((ap_const_lv4_1 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_4_reg_824) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158))) begin
        cr2dropper_V_data_V_din = p_Result_15_fu_737_p4;
    end else if (((ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158))) begin
        cr2dropper_V_data_V_din = p_Result_16_fu_722_p5;
    end else if ((((replyState_load_reg_753 == ap_const_lv4_6) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_5 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_8_reg_786) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_3 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_6_reg_816) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_2 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_5_reg_820) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)))) begin
        cr2dropper_V_data_V_din = p_Val2_9_reg_757;
    end else begin
        cr2dropper_V_data_V_din = 'bx;
    end
end

/// cr2dropper_V_last_V_din assign process. ///
always @ (ap_done_reg or replyState_load_reg_753 or tmp_8_reg_786 or tmp_7_reg_794 or tmp_6_reg_816 or tmp_5_reg_820 or tmp_4_reg_824 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1 or tmp_last_V_reg_776) begin
    if ((((ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_1 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_4_reg_824) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)))) begin
        cr2dropper_V_last_V_din = ap_const_lv1_0;
    end else if ((((replyState_load_reg_753 == ap_const_lv4_6) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_5 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_8_reg_786) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_3 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_6_reg_816) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_2 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_5_reg_820) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)))) begin
        cr2dropper_V_last_V_din = tmp_last_V_reg_776;
    end else begin
        cr2dropper_V_last_V_din = 'bx;
    end
end

/// cr2dropper_V_strb_V_din assign process. ///
always @ (ap_done_reg or replyState_load_reg_753 or tmp_8_reg_786 or tmp_7_reg_794 or tmp_6_reg_816 or tmp_5_reg_820 or tmp_4_reg_824 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1 or tmp_strb_V_reg_766) begin
    if ((((ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_1 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_4_reg_824) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)))) begin
        cr2dropper_V_strb_V_din = ap_const_lv8_FF;
    end else if ((((replyState_load_reg_753 == ap_const_lv4_6) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_5 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_8_reg_786) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_3 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_6_reg_816) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_2 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_5_reg_820) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)))) begin
        cr2dropper_V_strb_V_din = tmp_strb_V_reg_766;
    end else begin
        cr2dropper_V_strb_V_din = 'bx;
    end
end

/// cr2dropper_V_user_V_din assign process. ///
always @ (ap_done_reg or replyState_load_reg_753 or tmp_8_reg_786 or tmp_7_reg_794 or tmp_6_reg_816 or tmp_5_reg_820 or tmp_4_reg_824 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1 or tmp_user_V_reg_771) begin
    if ((((ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_1 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_4_reg_824) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)))) begin
        cr2dropper_V_user_V_din = ap_const_lv128_lc_1;
    end else if ((((replyState_load_reg_753 == ap_const_lv4_6) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_5 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_8_reg_786) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_3 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_6_reg_816) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_2 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_5_reg_820) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)))) begin
        cr2dropper_V_user_V_din = tmp_user_V_reg_771;
    end else begin
        cr2dropper_V_user_V_din = 'bx;
    end
end

/// parser2icmp_V_data_V0_update assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st1_fsm0_0 or grp_nbreadreq_fu_154_p6 or ap_sig_bdd_78 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1 or replyState) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (replyState == ap_const_lv4_5) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_4) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_3) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_2) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))))) begin
        parser2icmp_V_data_V0_update = ap_const_logic_1;
    end else begin
        parser2icmp_V_data_V0_update = ap_const_logic_0;
    end
end

/// validBuffer_V_V_din assign process. ///
always @ (or_cond1_reg_812 or ap_sig_bdd_633) begin
    if (ap_sig_bdd_633) begin
        if (~(ap_const_lv1_0 == or_cond1_reg_812)) begin
            validBuffer_V_V_din = ap_const_lv1_1;
        end else if ((ap_const_lv1_0 == or_cond1_reg_812)) begin
            validBuffer_V_V_din = ap_const_lv1_0;
        end else begin
            validBuffer_V_V_din = 'bx;
        end
    end else begin
        validBuffer_V_V_din = 'bx;
    end
end

/// validBuffer_V_V_write assign process. ///
always @ (ap_done_reg or replyState_load_reg_753 or tmp_7_reg_794 or tmp_last_V_23_reg_798 or or_cond1_reg_812 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1) begin
    if ((((ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794) & (ap_const_lv1_0 == tmp_last_V_23_reg_798) & (ap_const_lv1_0 == or_cond1_reg_812) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)) | ((ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794) & (ap_const_lv1_0 == tmp_last_V_23_reg_798) & ~(ap_const_lv1_0 == or_cond1_reg_812) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158)))) begin
        validBuffer_V_V_write = ap_const_logic_1;
    end else begin
        validBuffer_V_V_write = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm1) of the state machine. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st1_fsm0_0 or ap_CS_fsm1 or ap_sig_bdd_78 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1) begin
    case (ap_CS_fsm1)
        ap_ST_st2_fsm1_1 : 
        begin
            if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158) & ~ap_sig_bdd_78)) begin
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            end else if ((~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158) & (~(ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ap_sig_bdd_78)))) begin
                ap_NS_fsm1 = ap_ST_st0_fsm1_0;
            end else begin
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            end
        end
        ap_ST_st0_fsm1_0 : 
        begin
            if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            end else begin
                ap_NS_fsm1 = ap_ST_st0_fsm1_0;
            end
        end
        default : 
        begin
            ap_NS_fsm1 = 'bx;
        end
    endcase
end

/// the next state (ap_NS_fsm0) of the state machine. ///
always @ (ap_done_reg or ap_CS_fsm0 or ap_sig_bdd_78 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1) begin
    case (ap_CS_fsm0)
        ap_ST_st1_fsm0_0 : 
        begin
            ap_NS_fsm0 = ap_ST_st1_fsm0_0;
        end
        default : 
        begin
            ap_NS_fsm0 = 'bx;
        end
    endcase
end

assign ap_reg_ppstg_replyState_load_reg_753_pp0_it0 = replyState_load_reg_753;
assign ap_reg_ppstg_tmp_reg_833_pp0_it0 = tmp_reg_833;

/// ap_sig_bdd_110 assign process. ///
always @ (replyState_load_reg_753 or tmp_7_reg_794) begin
    ap_sig_bdd_110 = ((ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794));
end

/// ap_sig_bdd_158 assign process. ///
always @ (cr2checksum_V_V_full_n or replyState_load_reg_753 or cr2dropper_V_data_V1_status or tmp_8_reg_786 or tmp_7_reg_794 or validBuffer_V_V_full_n or tmp_last_V_23_reg_798 or or_cond1_reg_812 or tmp_6_reg_816 or tmp_5_reg_820 or tmp_4_reg_824) begin
    ap_sig_bdd_158 = (((cr2checksum_V_V_full_n == ap_const_logic_0) & (replyState_load_reg_753 == ap_const_lv4_C)) | ((cr2checksum_V_V_full_n == ap_const_logic_0) & (replyState_load_reg_753 == ap_const_lv4_B)) | ((cr2dropper_V_data_V1_status == ap_const_logic_0) & (replyState_load_reg_753 == ap_const_lv4_6)) | ((cr2dropper_V_data_V1_status == ap_const_logic_0) & (ap_const_lv4_5 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_8_reg_786)) | ((cr2dropper_V_data_V1_status == ap_const_logic_0) & (ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794)) | ((ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794) & (validBuffer_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == tmp_last_V_23_reg_798) & (ap_const_lv1_0 == or_cond1_reg_812)) | ((ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794) & (validBuffer_V_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == tmp_last_V_23_reg_798) & ~(ap_const_lv1_0 == or_cond1_reg_812)) | ((cr2dropper_V_data_V1_status == ap_const_logic_0) & (ap_const_lv4_3 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_6_reg_816)) | ((cr2dropper_V_data_V1_status == ap_const_logic_0) & (ap_const_lv4_2 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_5_reg_820)) | ((cr2dropper_V_data_V1_status == ap_const_logic_0) & (ap_const_lv4_1 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_4_reg_824)));
end

/// ap_sig_bdd_164 assign process. ///
always @ (ap_CS_fsm1) begin
    ap_sig_bdd_164 = (ap_const_lv1_1 == ap_CS_fsm1[ap_const_lv32_1]);
end

/// ap_sig_bdd_171 assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st1_fsm0_0 or ap_sig_bdd_78 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1) begin
    ap_sig_bdd_171 = ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_78 | (ap_sig_bdd_158 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))));
end

/// ap_sig_bdd_23 assign process. ///
always @ (ap_CS_fsm0) begin
    ap_sig_bdd_23 = (ap_CS_fsm0[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_297 assign process. ///
always @ (ap_done_reg or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1) begin
    ap_sig_bdd_297 = ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158));
end

/// ap_sig_bdd_34 assign process. ///
always @ (ap_CS_fsm1) begin
    ap_sig_bdd_34 = (ap_const_lv1_1 == ap_CS_fsm1[ap_const_lv32_0]);
end

/// ap_sig_bdd_380 assign process. ///
always @ (ap_reg_ppstg_replyState_load_reg_753_pp0_it0 or ap_reg_ppstg_tmp_reg_833_pp0_it0) begin
    ap_sig_bdd_380 = ((ap_const_lv4_0 == ap_reg_ppstg_replyState_load_reg_753_pp0_it0) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_reg_833_pp0_it0));
end

/// ap_sig_bdd_56 assign process. ///
always @ (grp_nbreadreq_fu_154_p6 or replyState) begin
    ap_sig_bdd_56 = (~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_3));
end

/// ap_sig_bdd_633 assign process. ///
always @ (ap_done_reg or replyState_load_reg_753 or tmp_7_reg_794 or tmp_last_V_23_reg_798 or ap_sig_bdd_158 or ap_sig_cseq_ST_st2_fsm1_1) begin
    ap_sig_bdd_633 = ((ap_const_lv4_4 == replyState_load_reg_753) & ~(ap_const_lv1_0 == tmp_7_reg_794) & (ap_const_lv1_0 == tmp_last_V_23_reg_798) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_158));
end

/// ap_sig_bdd_78 assign process. ///
always @ (ap_start or ap_done_reg or parser2icmp_V_data_V0_status or grp_nbreadreq_fu_154_p6 or replyState) begin
    ap_sig_bdd_78 = (((parser2icmp_V_data_V0_status == ap_const_logic_0) & (replyState == ap_const_lv4_5) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0)) | ((parser2icmp_V_data_V0_status == ap_const_logic_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_4)) | ((parser2icmp_V_data_V0_status == ap_const_logic_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_3)) | ((parser2icmp_V_data_V0_status == ap_const_logic_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_2)) | ((parser2icmp_V_data_V0_status == ap_const_logic_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_1)) | ((parser2icmp_V_data_V0_status == ap_const_logic_0) & ~(grp_nbreadreq_fu_154_p6 == ap_const_lv1_0) & (replyState == ap_const_lv4_0)) | (ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end
assign buffer_V_1_fu_414_p4 = {{crCurrWord_data_V[ap_const_lv32_2F : ap_const_lv32_20]}};
assign buffer_V_fu_588_p4 = {{crCurrWord_data_V[ap_const_lv32_2F : ap_const_lv32_10]}};
assign cr2dropper_V_data_V1_status = (cr2dropper_V_data_V_full_n & cr2dropper_V_strb_V_full_n & cr2dropper_V_user_V_full_n & cr2dropper_V_last_V_full_n);
assign cr2dropper_V_data_V_write = cr2dropper_V_data_V1_update;
assign cr2dropper_V_last_V_write = cr2dropper_V_data_V1_update;
assign cr2dropper_V_strb_V_write = cr2dropper_V_data_V1_update;
assign cr2dropper_V_user_V_write = cr2dropper_V_data_V1_update;
assign grp_fu_233_p1 = parser2icmp_V_last_V_dout;
assign grp_fu_267_p4 = {{p_Val2_9_reg_757[ap_const_lv32_3F : ap_const_lv32_30]}};
assign grp_nbreadreq_fu_154_p6 = (parser2icmp_V_data_V_empty_n & parser2icmp_V_strb_V_empty_n & parser2icmp_V_user_V_empty_n & parser2icmp_V_last_V_empty_n);
assign or_cond1_fu_508_p2 = (tmp1_fu_502_p2 & tmp_12_fu_484_p2);
assign p_1_fu_641_p2 = (icmpChecksum_V ^ ap_const_lv18_3FFFF);
assign p_2_fu_532_p2 = (p_Result_1_fu_524_p3 ^ ap_const_lv18_3FFFF);
assign p_3_fu_710_p2 = (p_Result_13_fu_703_p3 ^ ap_const_lv18_3FFFF);
assign p_Result_10_fu_424_p4 = {{parser2icmp_V_data_V_dout[ap_const_lv32_17 : ap_const_lv32_10]}};
assign p_Result_11_fu_434_p4 = {{parser2icmp_V_data_V_dout[ap_const_lv32_1F : ap_const_lv32_18]}};
assign p_Result_13_fu_703_p3 = {{ap_const_lv2_3}, {p_Result_12_reg_802}};
assign p_Result_14_fu_466_p5 = {{parser2icmp_V_data_V_dout[32'd63 : 32'd24]}, {tmp_11_fu_458_p3}};
assign p_Result_15_fu_737_p4 = {{{tmp_24_fu_734_p1}, {tmp_25_reg_828}}, {grp_fu_267_p4}};
assign p_Result_16_fu_722_p5 = {{{{p_Result_8_fu_694_p4}, {tmp_28_reg_807}}, {grp_fu_267_p4}}, {tmp_27_fu_691_p1}};
assign p_Result_1_fu_524_p3 = {{ap_const_lv2_3}, {tmp_26_fu_520_p1}};
assign p_Result_3_fu_346_p1 = p_Result_s_fu_336_p4;
assign p_Result_4_fu_663_p1 = p_Result_s_92_fu_653_p4;
assign p_Result_7_fu_602_p5 = {{parser2icmp_V_data_V_dout[32'd63 : 32'd32]}, {buffer_V_fu_588_p4}};
assign p_Result_8_fu_694_p4 = {{p_Val2_9_reg_757[ap_const_lv32_1F : ap_const_lv32_10]}};
assign p_Result_s_92_fu_653_p4 = {{icmpChecksum_V[ap_const_lv32_11 : ap_const_lv32_10]}};
assign p_Result_s_fu_336_p4 = {{ipChecksum_V[ap_const_lv32_11 : ap_const_lv32_10]}};
assign p_s_fu_318_p2 = (ipChecksum_V ^ ap_const_lv18_3FFFF);
assign parser2icmp_V_data_V0_status = (parser2icmp_V_data_V_empty_n & parser2icmp_V_strb_V_empty_n & parser2icmp_V_user_V_empty_n & parser2icmp_V_last_V_empty_n);
assign parser2icmp_V_data_V_read = parser2icmp_V_data_V0_update;
assign parser2icmp_V_last_V_read = parser2icmp_V_data_V0_update;
assign parser2icmp_V_strb_V_read = parser2icmp_V_data_V0_update;
assign parser2icmp_V_user_V_read = parser2icmp_V_data_V0_update;
assign replyState_load_load_fu_276_p1 = replyState;
assign tmp1_fu_502_p2 = (tmp_13_fu_490_p2 & tmp_14_fu_496_p2);
assign tmp_10_fu_667_p2 = (icmpChecksum_V + p_Result_4_fu_663_p1);
assign tmp_11_fu_458_p3 = {{ap_const_lv8_0}, {buffer_V_1_fu_414_p4}};
assign tmp_12_fu_484_p2 = (ipProto_V == ap_const_lv8_1? 1'b1: 1'b0);
assign tmp_13_fu_490_p2 = (p_Result_10_fu_424_p4 == ap_const_lv8_8? 1'b1: 1'b0);
assign tmp_14_fu_496_p2 = (p_Result_11_fu_434_p4 == ap_const_lv8_0? 1'b1: 1'b0);
assign tmp_1_fu_368_p2 = (ipChecksum_V + ap_const_lv18_40);
assign tmp_24_fu_734_p1 = p_Val2_9_reg_757[15:0];
assign tmp_25_fu_598_p1 = parser2icmp_V_data_V_dout[31:0];
assign tmp_26_fu_520_p1 = parser2icmp_V_data_V_dout[15:0];
assign tmp_27_fu_691_p1 = p_Val2_9_reg_757[15:0];
assign tmp_28_fu_454_p1 = parser2icmp_V_data_V_dout[15:0];
assign tmp_2_fu_350_p2 = (ipChecksum_V + p_Result_3_fu_346_p1);
assign tmp_3_fu_679_p2 = ($signed(icmpChecksum_V) + $signed(ap_const_lv18_3FFF8));
assign tmp_9_fu_390_p2 = (ipChecksum_V - tmp_s_fu_386_p1);
assign tmp_V_2_fu_636_p1 = icmpChecksum_V[15:0];
assign tmp_V_fu_308_p1 = ipChecksum_V[15:0];
assign tmp_s_fu_386_p1 = oldTTL;


endmodule //hlsExample_createReply

