// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.3
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hlsExample_dropper (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        validBuffer_V_V_dout,
        validBuffer_V_V_empty_n,
        validBuffer_V_V_read,
        cr2dropper_V_data_V_dout,
        cr2dropper_V_data_V_empty_n,
        cr2dropper_V_data_V_read,
        cr2dropper_V_strb_V_dout,
        cr2dropper_V_strb_V_empty_n,
        cr2dropper_V_strb_V_read,
        cr2dropper_V_user_V_dout,
        cr2dropper_V_user_V_empty_n,
        cr2dropper_V_user_V_read,
        cr2dropper_V_last_V_dout,
        cr2dropper_V_last_V_empty_n,
        cr2dropper_V_last_V_read,
        drop2checksum_V_data_V_din,
        drop2checksum_V_data_V_full_n,
        drop2checksum_V_data_V_write,
        drop2checksum_V_strb_V_din,
        drop2checksum_V_strb_V_full_n,
        drop2checksum_V_strb_V_write,
        drop2checksum_V_user_V_din,
        drop2checksum_V_user_V_full_n,
        drop2checksum_V_user_V_write,
        drop2checksum_V_last_V_din,
        drop2checksum_V_last_V_full_n,
        drop2checksum_V_last_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm0_0 = 1'b1;
parameter    ap_ST_st2_fsm1_1 = 2'b10;
parameter    ap_ST_st0_fsm1_0 = 2'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [0:0] validBuffer_V_V_dout;
input   validBuffer_V_V_empty_n;
output   validBuffer_V_V_read;
input  [63:0] cr2dropper_V_data_V_dout;
input   cr2dropper_V_data_V_empty_n;
output   cr2dropper_V_data_V_read;
input  [7:0] cr2dropper_V_strb_V_dout;
input   cr2dropper_V_strb_V_empty_n;
output   cr2dropper_V_strb_V_read;
input  [127:0] cr2dropper_V_user_V_dout;
input   cr2dropper_V_user_V_empty_n;
output   cr2dropper_V_user_V_read;
input  [0:0] cr2dropper_V_last_V_dout;
input   cr2dropper_V_last_V_empty_n;
output   cr2dropper_V_last_V_read;
output  [63:0] drop2checksum_V_data_V_din;
input   drop2checksum_V_data_V_full_n;
output   drop2checksum_V_data_V_write;
output  [7:0] drop2checksum_V_strb_V_din;
input   drop2checksum_V_strb_V_full_n;
output   drop2checksum_V_strb_V_write;
output  [127:0] drop2checksum_V_user_V_din;
input   drop2checksum_V_user_V_full_n;
output   drop2checksum_V_user_V_write;
output  [0:0] drop2checksum_V_last_V_din;
input   drop2checksum_V_last_V_full_n;
output   drop2checksum_V_last_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg validBuffer_V_V_read;
reg[0:0] drop2checksum_V_last_V_din;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm0 = 1'b1;
reg    ap_sig_cseq_ST_st1_fsm0_0;
reg    ap_sig_bdd_23;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm1 = 2'b1;
reg    ap_sig_cseq_ST_st0_fsm1_0;
reg    ap_sig_bdd_34;
wire    cr2dropper_V_data_V0_status;
wire   [0:0] grp_nbreadreq_fu_52_p6;
wire   [0:0] tmp_21_nbreadreq_fu_78_p3;
reg    ap_sig_bdd_74;
wire    drop2checksum_V_data_V1_status;
reg   [1:0] dropState_load_reg_166;
reg   [0:0] tmp_19_reg_178;
reg   [0:0] tmp_reg_187;
reg   [0:0] tmp_21_reg_191;
reg   [0:0] tmp_V_reg_195;
reg    ap_sig_bdd_104;
reg    ap_sig_cseq_ST_st2_fsm1_1;
reg    ap_sig_bdd_110;
reg   [1:0] dropState = 2'b00;
reg   [63:0] reg_141;
reg   [7:0] reg_146;
reg   [127:0] reg_151;
wire   [0:0] grp_fu_119_p1;
reg   [0:0] tmp_last_V_reg_182;
wire   [0:0] tmp_V_read_fu_86_p2;
reg   [0:0] tmp_last_V_18_reg_199;
wire   [1:0] ap_reg_phiprechg_storemerge_reg_108pp0_it0;
reg   [1:0] storemerge_phi_fu_111_p4;
reg    cr2dropper_V_data_V0_update;
reg    drop2checksum_V_data_V1_update;
reg   [0:0] ap_NS_fsm0;
reg   [1:0] ap_NS_fsm1;
reg    ap_sig_bdd_85;
reg    ap_sig_bdd_102;
reg    ap_sig_bdd_218;
reg    ap_sig_bdd_239;




/// the current state (ap_CS_fsm0) of the state machine. ///
always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm0
    if (ap_rst == 1'b1) begin
        ap_CS_fsm0 <= ap_ST_st1_fsm0_0;
    end else begin
        ap_CS_fsm0 <= ap_NS_fsm0;
    end
end

/// the current state (ap_CS_fsm1) of the state machine. ///
always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm1
    if (ap_rst == 1'b1) begin
        ap_CS_fsm1 <= ap_ST_st0_fsm1_0;
    end else begin
        ap_CS_fsm1 <= ap_NS_fsm1;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_104))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_0) & ~(ap_const_lv1_0 == tmp_21_nbreadreq_fu_78_p3) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        dropState <= storemerge_phi_fu_111_p4;
    end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (dropState == ap_const_lv2_2) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & ~(ap_const_lv1_0 == grp_fu_119_p1)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))) & ~(ap_const_lv1_0 == grp_fu_119_p1)))) begin
        dropState <= ap_const_lv2_0;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        dropState_load_reg_166 <= dropState;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_0) & ~(ap_const_lv1_0 == tmp_21_nbreadreq_fu_78_p3) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))))) begin
        reg_141 <= cr2dropper_V_data_V_dout;
        reg_146 <= cr2dropper_V_strb_V_dout;
        reg_151 <= cr2dropper_V_user_V_dout;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (dropState == ap_const_lv2_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_19_reg_178 <= grp_nbreadreq_fu_52_p6;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_21_reg_191 <= tmp_21_nbreadreq_fu_78_p3;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_0) & ~(ap_const_lv1_0 == tmp_21_nbreadreq_fu_78_p3) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_V_reg_195 <= validBuffer_V_V_dout;
        tmp_last_V_18_reg_199 <= cr2dropper_V_last_V_dout;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_last_V_reg_182 <= cr2dropper_V_last_V_dout;
    end
end

/// assign process. ///
always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (dropState == ap_const_lv2_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        tmp_reg_187 <= grp_nbreadreq_fu_52_p6;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_sig_bdd_104 or ap_sig_cseq_ST_st2_fsm1_1) begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_104)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm0_0 or ap_sig_cseq_ST_st0_fsm1_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (ap_const_logic_1 == ap_sig_cseq_ST_st0_fsm1_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st1_fsm0_0 or ap_sig_bdd_74 or ap_sig_bdd_104 or ap_sig_cseq_ST_st2_fsm1_1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st0_fsm1_0 assign process. ///
always @ (ap_sig_bdd_34) begin
    if (ap_sig_bdd_34) begin
        ap_sig_cseq_ST_st0_fsm1_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st0_fsm1_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm0_0 assign process. ///
always @ (ap_sig_bdd_23) begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_st1_fsm0_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm0_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm1_1 assign process. ///
always @ (ap_sig_bdd_110) begin
    if (ap_sig_bdd_110) begin
        ap_sig_cseq_ST_st2_fsm1_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm1_1 = ap_const_logic_0;
    end
end

/// cr2dropper_V_data_V0_update assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st1_fsm0_0 or grp_nbreadreq_fu_52_p6 or tmp_21_nbreadreq_fu_78_p3 or ap_sig_bdd_74 or ap_sig_bdd_104 or ap_sig_cseq_ST_st2_fsm1_1 or dropState) begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_0) & ~(ap_const_lv1_0 == tmp_21_nbreadreq_fu_78_p3) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & (dropState == ap_const_lv2_2) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1)))))) begin
        cr2dropper_V_data_V0_update = ap_const_logic_1;
    end else begin
        cr2dropper_V_data_V0_update = ap_const_logic_0;
    end
end

/// drop2checksum_V_data_V1_update assign process. ///
always @ (ap_done_reg or dropState_load_reg_166 or tmp_19_reg_178 or tmp_reg_187 or tmp_21_reg_191 or tmp_V_reg_195 or ap_sig_bdd_104 or ap_sig_cseq_ST_st2_fsm1_1) begin
    if ((((ap_const_lv2_1 == dropState_load_reg_166) & ~(ap_const_lv1_0 == tmp_19_reg_178) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_104)) | ((ap_const_lv2_0 == dropState_load_reg_166) & ~(ap_const_lv1_0 == tmp_reg_187) & ~(ap_const_lv1_0 == tmp_21_reg_191) & ~(ap_const_lv1_0 == tmp_V_reg_195) & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_104)))) begin
        drop2checksum_V_data_V1_update = ap_const_logic_1;
    end else begin
        drop2checksum_V_data_V1_update = ap_const_logic_0;
    end
end

/// drop2checksum_V_last_V_din assign process. ///
always @ (tmp_last_V_reg_182 or tmp_last_V_18_reg_199 or ap_sig_bdd_85 or ap_sig_bdd_102 or ap_sig_bdd_218) begin
    if (ap_sig_bdd_218) begin
        if (ap_sig_bdd_102) begin
            drop2checksum_V_last_V_din = tmp_last_V_18_reg_199;
        end else if (ap_sig_bdd_85) begin
            drop2checksum_V_last_V_din = tmp_last_V_reg_182;
        end else begin
            drop2checksum_V_last_V_din = 'bx;
        end
    end else begin
        drop2checksum_V_last_V_din = 'bx;
    end
end

/// storemerge_phi_fu_111_p4 assign process. ///
always @ (tmp_V_read_fu_86_p2 or ap_reg_phiprechg_storemerge_reg_108pp0_it0 or ap_sig_bdd_239) begin
    if (ap_sig_bdd_239) begin
        if ((ap_const_lv1_0 == tmp_V_read_fu_86_p2)) begin
            storemerge_phi_fu_111_p4 = ap_const_lv2_2;
        end else if (~(ap_const_lv1_0 == tmp_V_read_fu_86_p2)) begin
            storemerge_phi_fu_111_p4 = ap_const_lv2_1;
        end else begin
            storemerge_phi_fu_111_p4 = ap_reg_phiprechg_storemerge_reg_108pp0_it0;
        end
    end else begin
        storemerge_phi_fu_111_p4 = ap_reg_phiprechg_storemerge_reg_108pp0_it0;
    end
end

/// validBuffer_V_V_read assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st1_fsm0_0 or grp_nbreadreq_fu_52_p6 or tmp_21_nbreadreq_fu_78_p3 or ap_sig_bdd_74 or ap_sig_bdd_104 or ap_sig_cseq_ST_st2_fsm1_1 or dropState) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_0) & ~(ap_const_lv1_0 == tmp_21_nbreadreq_fu_78_p3) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
        validBuffer_V_V_read = ap_const_logic_1;
    end else begin
        validBuffer_V_V_read = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm0) of the state machine. ///
always @ (ap_done_reg or ap_CS_fsm0 or ap_sig_bdd_74 or ap_sig_bdd_104 or ap_sig_cseq_ST_st2_fsm1_1) begin
    case (ap_CS_fsm0)
        ap_ST_st1_fsm0_0 : 
        begin
            ap_NS_fsm0 = ap_ST_st1_fsm0_0;
        end
        default : 
        begin
            ap_NS_fsm0 = 'bx;
        end
    endcase
end

/// the next state (ap_NS_fsm1) of the state machine. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st1_fsm0_0 or ap_CS_fsm1 or ap_sig_bdd_74 or ap_sig_bdd_104 or ap_sig_cseq_ST_st2_fsm1_1) begin
    case (ap_CS_fsm1)
        ap_ST_st2_fsm1_1 : 
        begin
            if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_104) & ~ap_sig_bdd_74)) begin
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            end else if ((~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_104) & (~(ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) | ((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ap_sig_bdd_74)))) begin
                ap_NS_fsm1 = ap_ST_st0_fsm1_0;
            end else begin
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            end
        end
        ap_ST_st0_fsm1_0 : 
        begin
            if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_74 | (ap_sig_bdd_104 & (ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1))))) begin
                ap_NS_fsm1 = ap_ST_st2_fsm1_1;
            end else begin
                ap_NS_fsm1 = ap_ST_st0_fsm1_0;
            end
        end
        default : 
        begin
            ap_NS_fsm1 = 'bx;
        end
    endcase
end

assign ap_reg_phiprechg_storemerge_reg_108pp0_it0 = 'bx;

/// ap_sig_bdd_102 assign process. ///
always @ (dropState_load_reg_166 or tmp_reg_187 or tmp_21_reg_191 or tmp_V_reg_195) begin
    ap_sig_bdd_102 = ((ap_const_lv2_0 == dropState_load_reg_166) & ~(ap_const_lv1_0 == tmp_reg_187) & ~(ap_const_lv1_0 == tmp_21_reg_191) & ~(ap_const_lv1_0 == tmp_V_reg_195));
end

/// ap_sig_bdd_104 assign process. ///
always @ (drop2checksum_V_data_V1_status or dropState_load_reg_166 or tmp_19_reg_178 or tmp_reg_187 or tmp_21_reg_191 or tmp_V_reg_195) begin
    ap_sig_bdd_104 = (((drop2checksum_V_data_V1_status == ap_const_logic_0) & (ap_const_lv2_1 == dropState_load_reg_166) & ~(ap_const_lv1_0 == tmp_19_reg_178)) | ((drop2checksum_V_data_V1_status == ap_const_logic_0) & (ap_const_lv2_0 == dropState_load_reg_166) & ~(ap_const_lv1_0 == tmp_reg_187) & ~(ap_const_lv1_0 == tmp_21_reg_191) & ~(ap_const_lv1_0 == tmp_V_reg_195)));
end

/// ap_sig_bdd_110 assign process. ///
always @ (ap_CS_fsm1) begin
    ap_sig_bdd_110 = (ap_const_lv1_1 == ap_CS_fsm1[ap_const_lv32_1]);
end

/// ap_sig_bdd_218 assign process. ///
always @ (ap_done_reg or ap_sig_bdd_104 or ap_sig_cseq_ST_st2_fsm1_1) begin
    ap_sig_bdd_218 = ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm1_1) & ~((ap_done_reg == ap_const_logic_1) | ap_sig_bdd_104));
end

/// ap_sig_bdd_23 assign process. ///
always @ (ap_CS_fsm0) begin
    ap_sig_bdd_23 = (ap_CS_fsm0[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_239 assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm0_0 or grp_nbreadreq_fu_52_p6 or tmp_21_nbreadreq_fu_78_p3 or dropState) begin
    ap_sig_bdd_239 = ((ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm0_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_0) & ~(ap_const_lv1_0 == tmp_21_nbreadreq_fu_78_p3));
end

/// ap_sig_bdd_34 assign process. ///
always @ (ap_CS_fsm1) begin
    ap_sig_bdd_34 = (ap_const_lv1_1 == ap_CS_fsm1[ap_const_lv32_0]);
end

/// ap_sig_bdd_74 assign process. ///
always @ (ap_start or ap_done_reg or cr2dropper_V_data_V0_status or grp_nbreadreq_fu_52_p6 or validBuffer_V_V_empty_n or tmp_21_nbreadreq_fu_78_p3 or dropState) begin
    ap_sig_bdd_74 = (((cr2dropper_V_data_V0_status == ap_const_logic_0) & (dropState == ap_const_lv2_2) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0)) | ((cr2dropper_V_data_V0_status == ap_const_logic_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_1)) | (~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (validBuffer_V_V_empty_n == ap_const_logic_0) & (dropState == ap_const_lv2_0) & ~(ap_const_lv1_0 == tmp_21_nbreadreq_fu_78_p3)) | ((cr2dropper_V_data_V0_status == ap_const_logic_0) & ~(grp_nbreadreq_fu_52_p6 == ap_const_lv1_0) & (dropState == ap_const_lv2_0) & ~(ap_const_lv1_0 == tmp_21_nbreadreq_fu_78_p3)) | (ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_85 assign process. ///
always @ (dropState_load_reg_166 or tmp_19_reg_178) begin
    ap_sig_bdd_85 = ((ap_const_lv2_1 == dropState_load_reg_166) & ~(ap_const_lv1_0 == tmp_19_reg_178));
end
assign cr2dropper_V_data_V0_status = (cr2dropper_V_data_V_empty_n & cr2dropper_V_strb_V_empty_n & cr2dropper_V_user_V_empty_n & cr2dropper_V_last_V_empty_n);
assign cr2dropper_V_data_V_read = cr2dropper_V_data_V0_update;
assign cr2dropper_V_last_V_read = cr2dropper_V_data_V0_update;
assign cr2dropper_V_strb_V_read = cr2dropper_V_data_V0_update;
assign cr2dropper_V_user_V_read = cr2dropper_V_data_V0_update;
assign drop2checksum_V_data_V1_status = (drop2checksum_V_data_V_full_n & drop2checksum_V_strb_V_full_n & drop2checksum_V_user_V_full_n & drop2checksum_V_last_V_full_n);
assign drop2checksum_V_data_V_din = reg_141;
assign drop2checksum_V_data_V_write = drop2checksum_V_data_V1_update;
assign drop2checksum_V_last_V_write = drop2checksum_V_data_V1_update;
assign drop2checksum_V_strb_V_din = reg_146;
assign drop2checksum_V_strb_V_write = drop2checksum_V_data_V1_update;
assign drop2checksum_V_user_V_din = reg_151;
assign drop2checksum_V_user_V_write = drop2checksum_V_data_V1_update;
assign grp_fu_119_p1 = cr2dropper_V_last_V_dout;
assign grp_nbreadreq_fu_52_p6 = (cr2dropper_V_data_V_empty_n & cr2dropper_V_strb_V_empty_n & cr2dropper_V_user_V_empty_n & cr2dropper_V_last_V_empty_n);
assign tmp_21_nbreadreq_fu_78_p3 = validBuffer_V_V_empty_n;
assign tmp_V_read_fu_86_p2 = validBuffer_V_V_dout;


endmodule //hlsExample_dropper

